version: '3.9'

services:
  mongo_db:
    container_name: mobischool_mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    container_name: mobischool_api
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 4000
      DATABASE_URL: mongodb+srv://ilearn:nn7RMniQ6GNji3Cm@cluster0.lxozdxf.mongodb.net/ilearn_development
      NODE_ENV: development
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}